# Generated by Django 4.0.4 on 2022-04-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='todo_app.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
