# Generated by Django 4.0.4 on 2022-04-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_task_employee_alter_employee_hired_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='task',
        ),
    ]
